### PR TITLE
esp-box-3 - Readme update (BSP-413)

### PR DESCRIPTION
**Pull request by VojtechBartoska**
# Change description
Draft of BSP ReadMe update for ESP-S3-Box-3.

#### This PR is a draft, here is a to-do list of left things:
- [ ] automatically added list of board capabilities ([link](https://github.com/espressif/esp-bsp/blob/a4b752a36ca45b87ac5e9b7bcfbac812c7a5b63c/bsp/esp-box-3/include/bsp/esp-box-3.h#L33))
- [ ] automatically added list of components ([link](https://github.com/espressif/esp-bsp/blob/a4b752a36ca45b87ac5e9b7bcfbac812c7a5b63c/bsp/esp-box-3/idf_component.yml#L9))
- [ ] automatically link supported examples
- [ ] badges update
- [ ] investigated used pictures (be aware of light/dark theme on browsers + duplicity on other sources)

### CODE REVIEW

**Comment by VojtechBartoska** [comment]
- link to HW schema is very useful, should be added to all BSPs if available
- pictures are not rendered in Component Manager

**Comment by tore-espressif** [comment]
@VojtechBartoska Should we start reviewing this PR, or do you plan to work on it more?

**Comment by VojtechBartoska** [comment]
@tore-espressif It is not ready yet, will let you know when you can review it.

**Comment by VojtechBartoska** [comment]
Closing this PR in favour of https://github.com/espressif/esp-bsp/pull/262.

I will update READMEs in above mentioned PR accordingly.

**Pull request closed without merging**
