### PR TITLE
LVGL: Updated BSPs and examples for new ESP LVGL Port (LVGL9)

### PR DESCRIPTION
**Pull request by espzav**
# ESP-BSP Pull Request checklist

- [x] Wait and update after merge #322 
- [x] Version of modified component bumped
- [x] CI passing
- [x] Add examples/display_audio_photo/sdkconfig.bsp.esp32_s3_lcd_ev_board
- [x] Add examples/display_rotation/sdkconfig.bsp.esp32_s3_lcd_ev_board
- [x] Wait and update after merge #333 

# Change description
- Update for all BSPs and examples for working with LVGL9 (Updated types and default configs). 
- Fixed minor issues

Closes #288

# Tested HW

## display
- [x] esp-box
- [x] esp-box-lite
- [x] esp-box-3
- [x] m5stack_core_s3
- [x] esp32_p4_function_ev_board
- [x] esp32_s2_kaluga_kit
- [x] esp32_s3_eye
- [x] esp32_s3_korvo_2
- [ ] esp32_s3_lcd_ev_board
- [ ] esp_wrover_kit
- [x] esp32_c3_lcdkit
- [x] esp32_s2_kaluga_kit

## display_audio_photo
- [x] esp-box
- [ ] esp-box-lite
- [x] esp-box-3
- [x] m5stack_core_s3
- [x] esp32_s3_korvo_2
- [x] esp32_s3_lcd_ev_board

## display_camera
- [x] esp32_s2_kaluga_kit
- [ ] esp32_s3_korvo_2
- [x] esp32_s3_eye
- [x] m5stack_core_s3

## display_rotation
- [x] esp32_s3_korvo_2
- [x] esp32_s3_lcd_ev_board
- [ ] esp-box
- [x] esp-box-lite
- [ ] esp-box-3
- [x] m5stack_core_s3

## display_usb_hid
- [x] esp32_p4_function_ev_board
- [x] esp32_s3_usb_otg

## display_lvgl_demos
- [x] esp-box
- [x] esp-box-lite
- [x] esp-box-3
- [x] m5stack_core_s3
- [x] esp32_p4_function_ev_board
- [x] esp32_s2_kaluga_kit
- [x] esp32_s3_eye
- [x] esp32_s3_korvo_2
- [x] esp32_s3_lcd_ev_board

### CODE REVIEW

**Comment by espzav** [comment]
@tore-espressif PTAL
@pborcin PTAL and please, could you try examples with combination of BSPs as many as possible (please write note, what did you test);

**Review by pborcin — COMMENTED** [review]
Tested on esp32-s3-korvo-2 and m5stack-core-s3 and informed Vilem about some examples issues. Otherwise LGTM.

**Comment by espzav** [comment]
> Tested on esp32-s3-korvo-2 and m5stack-core-s3 and informed Vilem about some examples issues. Otherwise LGTM.

@pborcin Thank you for testing. I have fixed camera example (color was swapped on some devices and rotation on M5Stack). 
There is still issue in `audio_photo_example` on M5Stack - crashing when open JPEG image - I am working on it.

**Comment by espzav** [comment]
> > Tested on esp32-s3-korvo-2 and m5stack-core-s3 and informed Vilem about some examples issues. Otherwise LGTM.
> 
> @pborcin Thank you for testing. I have fixed camera example (color was swapped on some devices and rotation on M5Stack). There is still issue in `audio_photo_example` on M5Stack - crashing when open JPEG image - I am working on it.

Fixed  `audio_photo_example` on M5Stack

**Comment by espzav** [comment]
I made some changes in `display_camera` example for swapping RGB565 color and rotating on the screen for M5Stack). Please, could anybody (@tore-espressif @pborcin ) try this example with these boards?
- esp32_s2_kaluga_kit
- esp32_s3_korvo_2
- esp32_s3_eye

**Comment by pborcin** [comment]
@espzav Tested display_camera, on esp32_s3_korvo_2 it works fine. On esp32_s3_eye the main screen works as well, but colors are mashed on the status panel (cpu, fps text is still discernible).

**Comment by tore-espressif** [comment]
* display_camera OK on kaluga and s3-eye
* display OK on s3-eye
* display_lvgl_demos OK on s3-eye

**Pull request merged**
