### PR TITLE
tca9554: Added I2C addresses for A version of the expander.

### PR DESCRIPTION
**Pull request by espzav**
Added I2C addresses for TCA9554A into header file.

### CODE REVIEW

**Review by Lzw655 — APPROVED** [review]
Thank you for making this component compatible with tca9554a. And I'm wondering if we should change its name to "tca9554(a)" in the README.

**Comment by espzav** [comment]
@Lzw655 Thank you for the review. I updated readme and description.

**Comment by Lzw655** [comment]
> @Lzw655 Thank you for the review. I updated readme and description.

Ok, LGTM!

**Review by tore-espressif — APPROVED** [review]
Thank you @espzav LGTM!

**Pull request merged**
