### PR TITLE
feat(lcd): add ili9881c driver (BSP-431)

### PR DESCRIPTION
**Pull request by suda-morris**
# ESP-BSP Pull Request checklist

> Note: For new BSPs create a PR with this [link](https://github.com/espressif/esp-bsp/compare/main...my-branch?quick_pull=1&template=pr_template_bsp.md).

- [x] Version of modified component bumped
- [x] CI passing

# Change description
_Please describe your change here_

### CODE REVIEW

**Comment by suda-morris** [comment]
@espzav Note, this is an early version (v0.1.0), we want to release it ASAP for user evaluation. Please take a look as well @Lzw655

**Review by tore-espressif — APPROVED** [review]
@suda-morris thank you for the driver!

For new LCD drivers we also add them to this table https://github.com/espressif/esp-bsp/blob/master/LCD.md

But if it is urgent, it is not necessary for v0.1.0

**Comment by suda-morris** [comment]
> @suda-morris thank you for the driver!
> 
> For new LCD drivers we also add them to this table https://github.com/espressif/esp-bsp/blob/master/LCD.md
> 
> But if it is urgent, it is not necessary for v0.1.0

Yes I know, but currently I can't find a beautiful image of this LCD panel, we can add it later. Thanks for the quick review!

**Review by tore-espressif — APPROVED** [review]

**Comment by aeroramesh** [comment]
Hi , I wanted to write you about your one of old project . Can I have your email id please ? . would be helpful

**Pull request merged**
