### PR TITLE
Added badges with versions to READMEs of components

### PR DESCRIPTION
**Pull request by XDanielPaul**
## Description
Added badges with versions in README files to following components:

- esp-box
- esp-32_azure_iot_kit
- esp32_azure_iot_kit
- esp32_s3_eye
- esp32_s3_lcd_ev_board
- esp32_s3_usb_otg
- esp_wrover_kit

## Edit
Added badge with latest version in README files to remaining components in [components](https://github.com/espressif/esp-bsp/tree/master/components) subfolder and it's subfolders

### CODE REVIEW

**Comment by igrr** [comment]
It would have been slightly nicer if the badge said `Latest version: vX.Y.Z` instead of `Version:  vX.Y.Z`. If we were to look at some old commit like https://github.com/espressif/esp-bsp/tree/8e739dd9ef35e58a06bf91226b4da5f7c5d92db8/esp_wrover_kit, the badge would still say `Version: 1.3.1` while the actual version of the component in that commit would be 1.2.1.

(Not a blocker for merging this PR, since the badge is defined on the IDF Component Registry side.)

**Review by igrr — APPROVED** [review]

**Comment by XDanielPaul** [comment]
> thank you @XDanielPaul

No problem!

**Comment by tore-espressif** [comment]
We have also lots of components in [components](https://github.com/espressif/esp-bsp/tree/master/components) subfolder, but we can update that later.

**Review by tore-espressif — APPROVED** [review]
Thank you @XDanielPaul

**Pull request merged**
