### PR TITLE
SquareLine: Add some compile options for main Cmake of common

### PR DESCRIPTION
**Pull request by Lzw655**
# Checklist for new Board Support package or Component

- [ ] Component contains License
- [ ] Component contains README.md
- [ ] Project [README.md](../README.md) updated
- [ ] Component contains idf_component.yml file with `url` field defined
- [ ] Component was added to CI [upload job](https://github.com/espressif/esp-bsp/blob/master/.github/workflows/upload_component.yml#L17)
- [ ] New files were added to CI build job
- [ ] _Optional:_ Component contains unit tests
- [ ] CI passing

# Change description
* Add `-Wno-unused-variable` and `-DLV_LVGL_H_INCLUDE_SIMPLE` two compile options in main CMakeLists.txt of common
* Solve the compile warning and error when using Squareline

### CODE REVIEW

**Comment by Lzw655** [comment]
I'm trying to run "3d_printer" example in SquareLine with esp32_s3_lcd_ev_board board (generated by esp-bsp/Squareline). But after generating the project, I compiled it and got the following error and warning.

Screenshot 2022-12-23 131049

The font files generated by Squareline will include the below headers. So I think it's better to add these compile options in main CMakeLists.txt.

```
#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif
```

**Comment by Lzw655** [comment]
@espzav @tore-espressif Hi, I found a little problem, PTAL. Thanks!

**Comment by espzav** [comment]
> #ifdef LV_LVGL_H_INCLUDE_SIMPLE
> #include "lvgl.h"
> #else
> #include "lvgl/lvgl.h"
> #endif

This issue was discussed with @kisvegabor before some months. I tested it again and I see, when I click to MODIFY button in Font Manager (for all fonts) in SquareLine studio, it is generated right.

**Comment by Lzw655** [comment]
> > #ifdef LV_LVGL_H_INCLUDE_SIMPLE
> > #include "lvgl.h"
> > #else
> > #include "lvgl/lvgl.h"
> > #endif
> 
> This issue was discussed with @kisvegabor before some months. I tested it again and I see, when I click to MODIFY button in Font Manager (for all fonts) in SquareLine studio, it is generated right.

Yeah, you're right. It is generated right after I click to MODIFY button.

**Pull request closed without merging**
