### PR TITLE
SquareLine: Added license file.

### PR DESCRIPTION
**Pull request by espzav**
Add license file into each board package for SquareLine.

### CODE REVIEW

**Comment by espzav** [comment]
@igrr PTAL

**Comment by igrr** [comment]
LGTM, but let's wait for @kisvegabor to confirm the location of the file.

**Comment by espzav** [comment]
> LGTM, but let's wait for @kisvegabor to confirm the location of the file.

@igrr Thank you. Now, the LICENSE file will be in root package for each board and in ZIP file too. I think, it can be in ZIP file, because ZIP file is used for generating project folder and the LICENSE will be copied there too.

**Comment by kisvegabor** [comment]
We need the license in the top level in each repo. So next to the `.slb` file.

However, adding it to the zip is also a good idea.

**Comment by espzav** [comment]
> We need the license in the top level in each repo. So next to the `.slb` file.
> 
> However, adding it to the zip is also a good idea.

It will be in the top level after this PR. 
@igrr I think, we can merge it, do you get me approve please?

**Review by igrr — APPROVED** [review]

**Comment by kisvegabor** [comment]
Thank you, I'll add the licenses to our repos.

**Pull request merged**
