### PR TITLE
SquareLine: Update LVGL version and board names.

### LINKED ISSUE #80: Minor updates on the structure of SquareLine Studio boards (BSP-213)
Hi,

We made a few little modification on directory structure of the boards in SquareLine Studio. The current version is also working but maybe you want to make the content of the `espressif` folder aligned with the other board folders. We manually updated the name of all existing boards and files and this is how it looks like now:
```shell
├── arduino
│   ├── tft_espi_v1_0_0
│   │   ├── tft_espi.png
│   │   ├── tft_espi.slb
│   │   └── tft_espi.zip
│   └── tft_espi_v1_0_1
│       ├── tft_espi.png
│       ├── tft_espi.slb
│       └── tft_espi.zip
├── desktop
│   ├── eclipse_sdl_v1_0_0
│   │   ├── eclipse_sdl.png
│   │   ├── eclipse_sdl.slb
│   │   └── eclipse_sdl.zip
│   ├── eclipse_sdl_v1_0_1
│   │   ├── eclipse_sdl.png
│   │   ├── eclipse_sdl.slb
│   │   └── eclipse_sdl.zip
│   ├── micropython_v1_0_0
│   │   ├── micropython.png
│   │   ├── micropython.slb
│   │   └── micropython.zip
│   └── micropython_v1_0_1
│       ├── micropython.png
│       ├── micropython.slb
│       └── micropython.zip
└── espressif
    ├── espbox_v1_0_0
    │   ├── espbox.png
    │   ├── espbox.slb
    │   └── espbox.zip
    └── espwroverkit_v1_0_0
        ├── espwroverkit.png
        ├── espwroverkit.slb
        └── espwroverkit.zip
```

So `<vendor>/<board_name>_<version>/<files_without_version>`. 

---
We also needed to update how LVGL versions are enumerated in the `.slb` file. Our initial idea was to support wildchars like `v8.0+` but finally we have choosen a more explicit way. So the supported LVGL versions needs to be written one by one like: 
```
"supported_lvgl_version": "8.2.0, 8.3.3",
```
(At this moment we support these 2 LVGL versions)

---

If you wish I can send a PR for `gen.py`, but I don't know if LVGL v8.3.3 is supported.

### PR DESCRIPTION
**Pull request by espzav**
Updated SquareLine generator for structure changes (GitHub issue Closes #80).

### CODE REVIEW

**Comment by kisvegabor** [comment]
I've test it and it looks good. Thank you!

It totally up to you, but I'd like to bring to your attention that you can add some more text to the short and long description fields:
image
image

**Comment by espzav** [comment]
@kisvegabor Thank you for test it. I know about descriptions. 
@igrr please, could you help me with right descriptions? I tried to use from BSP, but there are not good descriptions for all boards and I cannot find any good descriptions on our sites for these boards. Thank you

**Comment by kisvegabor** [comment]
We are planning to make a SquareLine Studio release in a few weeks. In order to add the new boards you have created for SquareLine it'd be great to have this PR merged even with the current descriptions. 

So if you are busy now and don't have  time to update the descriptions can you merge it as it is?

**Comment by VojtechBartoska** [comment]
@kisvegabor we'll merge it today/tomorrow, descriptions are ready. I'll commit them in  a moment. Sorry for the delay.

**Comment by kisvegabor** [comment]
Great, thank you very much! :relaxed:

**Review by VojtechBartoska — APPROVED** [review]
Thanks @espzav for changes.

**Review by tore-espressif — APPROVED** [review]
Thanks guys!

**Comment by espzav** [comment]
@VojtechBartoska Thank you for help with descriptions!

**Pull request merged**
