### PR TITLE
BME280 sensor library (BSP-198)

### PR DESCRIPTION
**Pull request by MUDAL**
BME280 library using ESP-IDF device drivers

Added a new folder to the "components" directory. This is the project folder for a new library to interface an
ESP32 with a BME280 sensor. The library is properly documented and it follows the coding styles used in other
ESP-IDF codes. I'd be glad if the code is reviewed and feedback is given.

Thank you.

### CODE REVIEW

**Comment by MUDAL** [comment]
What could possibly be the problem with these failed checks? Not sure how this build process works

**Comment by tore-espressif** [comment]
Hello @MUDAL thank you very much for your contribution, I'll do my best to review this week.

For a starter, please install and run [pre-commit](https://pre-commit.com/), it will format your code.

**Comment by igrr** [comment]
Hi @MUDAL, nice work writing the driver!

Not sure if you have seen this, there's a BMP280/BME280 driver available in esp-idf-lib: https://github.com/UncleRus/esp-idf-lib/tree/master/components/bmp280.

If that driver is missing any feature you need, would it make more sense to improve the existing driver rather than creating a totally new one?

**Comment by MUDAL** [comment]
Hi @su

> Hi @MUDAL, nice work writing the driver!
> 
> Not sure if you have seen this, there's a BMP280/BME280 driver available in esp-idf-lib: https://github.com/UncleRus/esp-idf-lib/tree/master/components/bmp280.
> 
> If that driver is missing any feature you need, would it make more sense to improve the existing driver rather than creating a totally new one?

oh wow @igrr, I didn't know there was an existing driver. I was checking the esp-idf repo and decided to put it in the i2c folder. But I was advised to transfer it to the bsp repo

**Comment by MUDAL** [comment]
> Hello @MUDAL thank you very much for your contribution, I'll do my best to review this week.
> 
> For a starter, please install and run [pre-commit](https://pre-commit.com/), it will format your code.

Thanks

**Comment by MUDAL** [comment]
This is my first time contributing, so I'll take a better look at the existing libraries

**Comment by tore-espressif** [comment]
@MUDAL If you are happy with the proposed solution, I'll close this PR.

Thanks and feel free to reopen

**Comment by MUDAL** [comment]
I'd really like to contribute to the one of the esp-idf repositories. However, I haven't gotten the hang of how to go about making a successful commit. My commits keep failing the automated checks.

Thank you.

**Pull request closed without merging**
