### PR TITLE
CST816: Extend the reset time and fix the interruption

### PR DESCRIPTION
**Pull request by Lzw655**
Closes https://github.com/espressif/esp-bsp/issues/178

# ESP-BSP Pull Request checklist

> Note: For new BSPs create a PR with this [link](https://github.com/espressif/esp-bsp/compare/main...my-branch?quick_pull=1&template=pr_template_bsp.md).

- [ ] Version of modified component bumped
- [ ] CI passing

# Change description
Fix bugs of `esp_lcd_touch_cst816s`

### CODE REVIEW

**Comment by Lzw655** [comment]
@espzav @tom-borcin PTAL, thanks!

**Comment by tom-borcin** [comment]
> @espzav @tom-borcin PTAL, thanks!

I think you meant @tore-espressif

**Review by espzav — COMMENTED** [review]
@Lzw655 Thank you very much for these changes! LGTM
Please, could you fix STMPE610 touch controller for interrupt_callback in the same PR? I overlooked before, there is the same issue. And then, please squash commits.

**Comment by Lzw655** [comment]
Sure, I'll do it. 👌

**Comment by Lzw655** [comment]
@espzav All fixed. PTAL, thank you.

**Review by espzav — APPROVED** [review]
@Lzw655 Thank you very much! LGTM

**Pull request merged**
