### PR TITLE
Examples/optimization

### LINKED ISSUE #50: Fix format warnings (BSP-175)
esp-idf is changin defintion of `uint32_t` from unsigned int to unsigned long.
Now we need to use PRIx32 specifier from inttypes.h instead of d or u, during print.

TODO:

- [x] Remove -Wno-format compiler option
- [x] Fix all format warings

### PR DESCRIPTION
**Pull request by tore-espressif**
# ESP-BSP Pull Request checklist

- [x] CI passing

# Change description

1. Fix format warnings and remove `-Wno-format` compile flag
2. Remove few examples

We want to remove few rudimentary examples to offload the maintainers, so they can focus in improving existing examples

Closes #50

### CODE REVIEW

**Review by espzav — COMMENTED** [review]
As I said before, I think that the example display_rotation can still be helpful for customers. I would like to add the example with rotation by the accelerometer, but we haven't got it in our boards now. Other LGTM.

**Comment by tore-espressif** [comment]
> As I said before, I think that the example display_rotation can still be helpful for customers. I would like to add the example with rotation by the accelerometer, but we haven't got it in our boards now. Other LGTM.

Thank you for the review @espzav . Display_rotation example restored!

**Review by espzav — APPROVED** [review]
LGTM

**Comment by igrr** [comment]
@tore-espressif could you please update README.md as well? https://github.com/espressif/esp-bsp#examples still lists the examples which have been removed.

**Comment by tore-espressif** [comment]
@igrr yes, the upload workflow is failing too. It seems that i was too hasty with merging 🤦

**Pull request merged**
