### PR TITLE
s3-lcd-ev-board: fix headers and remove partition table

### PR DESCRIPTION
**Pull request by Lzw655**
# Checklist for new Board Support package or Component

- [x] Component contains License
- [x] Component contains README.md
- [x] Project [README.md](../README.md) updated
- [x] Component contains idf_component.yml file with `url` field defined
- [x] Component was added to CI [upload job](https://github.com/espressif/esp-bsp/blob/master/.github/workflows/upload_component.yml#L17)
- [x] New files were added to CI build job
- [ ] _Optional:_ Component contains unit tests
- [x] CI passing

# Change description
* fix some unsuitable headers in bsp
* remove partition table in example "display_lvgl_demos" which is unnecessary
* update some links in README

### CODE REVIEW

**Comment by Lzw655** [comment]
@espzav @tore-espressif  Hi, I found some unsuitable code in bsp and example. So I make a little changes. PTAL, thank you very much!

**Comment by tore-espressif** [comment]
@Lzw655 is this ready for review?

**Comment by Lzw655** [comment]
@tore-espressif @espzav  Please wait a little longer, the document may need to be revised. And I will inform you then.

**Comment by Lzw655** [comment]
@tore-espressif @espzav Hi, the PR is ready for review. PTAL, thank you!

**Review by tore-espressif — APPROVED** [review]
LGTM @Lzw655

**Review by espzav — APPROVED** [review]
LGTM

**Pull request merged**
