### PR TITLE
esp-box: add low power interface; add box-3 support (BSP-372)

### PR DESCRIPTION
**Pull request by espressif2022**
# ESP-BSP Pull Request checklist

> Note: For new BSPs create a PR with this [link](https://github.com/espressif/esp-bsp/compare/main...my-branch?quick_pull=1&template=pr_template_bsp.md).

- [ ] Version of modified component bumped
- [ ] CI passing

# Change description
add low power interface
add box-3 support

### CODE REVIEW

**Comment by espzav** [comment]
Hi @espressif2022, thank you for changes. We decided, that the ESP-BOX 3 will be as a new BSP. Please, could you change it for new BSP? I will make review after that (but I will wait for HW) Is it ok for you?

**Comment by espzav** [comment]
@espressif2022 And another question: Please, why we need low power APIs in LCD, LVGL and touch now?

**Comment by espressif2022** [comment]
> @espressif2022 And another question: Please, why we need low power APIs in LCD, LVGL and touch now?

To support esp-box-3, it has a battery base and needs low power function.

**Comment by espressif2022** [comment]
> Hi @espressif2022, thank you for changes. We decided, that the ESP-BOX 3 will be as a new BSP. Please, could you change it for new BSP? I will make review after that (but I will wait for HW) Is it ok for you?

This is correct, box-3 needs a new BSP.
There is a special place, the 100 pcs released this time is based on old LCD and TP. (same with esp-box)
Subsequent box-3 will use new TP and LCD drivers, so a new one will be needed.

Now the question is really, should this one particular batch be based on the bsp esp-box or new esp-box-3.

**Pull request closed without merging**
