### PR TITLE
lcd: SSD1306 driver marked as deprecated.

### PR DESCRIPTION
**Pull request by espzav**
# ESP-BSP Pull Request checklist

- [x] Version of modified component bumped
- [ ] CI passing

### CODE REVIEW

**Comment by espzav** [comment]
@tore-espressif PTAL

**Comment by tore-espressif** [comment]
@espzav Could you also please add `__attribute__((deprecated))` to this function https://github.com/espressif/esp-bsp/blob/1452b261c778453c32a98fe897b571561db95bb5/components/ssd1306/include/ssd1306.h#L53 ?

This way, users that use the latest version of ssd1306 component in their projects, will get deprecation warning during build

What do you think?

**Comment by espzav** [comment]
> This way, users that use the latest version of ssd1306 component in their projects, will get deprecation warning during build
> 
> What do you think?

@tore-espressif Good point, Thank you. Updated.

**Review by tore-espressif — APPROVED** [review]
LGTM!

**Pull request merged**
